name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
#        version: [ 7.4, 8.2, 8.3, 8.4 ]
        version: [ 8.4 ]
#        flavor: [ apache, cli, fpm, frankenphp ]
        flavor: [ fpm ]
#        exclude:
#          - version: 7.4
#            flavor: frankenphp

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU for arm arch build
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.version }}/${{ matrix.flavor }}
          load: true
          tags: openmage-dev:${{ matrix.version }}-${{ matrix.flavor }}
      -
        name: Test
        run: |
          docker run --rm -v $(pwd)/test:/app openmage-dev:${{ matrix.version }}-${{ matrix.flavor }} php /app/test.php
      -
        name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: openmage-dev:${{ matrix.version }}-${{ matrix.flavor }}
          dockerfile: ./${{ matrix.version }}/${{ matrix.flavor }}/Dockerfile
          annotations: true
          severity: HIGH,CRITICAL
          #severity_threshold: CRITICAL
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.version }}/${{ matrix.flavor }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/ajbonner/docker-openmage:${{ matrix.version }}-${{ matrix.flavor }}
          cache-from: type=registry,ref=ajbonner/docker-openmage:${{ matrix.version }}-${{ matrix.flavor }}
          cache-to: type=inline
